# Generated by Django 6.0.1 on 2026-05-20 05:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CABANA', 'Cabaña'), ('CAMPING', 'Camping')], max_length=10)),
                ('categoria', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PAREJA', 'Pareja'), ('FAMILIAR', 'Familiar')], max_length=12)),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=15)),
                ('num_camas', models.PositiveIntegerField(blank=True, null=True)),
                ('num_banos', models.PositiveIntegerField(blank=True, null=True)),
                ('tiene_agua', models.BooleanField(default=False)),
                ('tiene_luz', models.BooleanField(default=False)),
                ('tiene_regadera', models.BooleanField(default=False)),
                ('pos_x', models.FloatField(blank=True, null=True)),
                ('pos_y', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hospedaje',
                'verbose_name_plural': 'Hospedajes',
                'db_table': 'hospedaje',
            },
        ),
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('imagen_mapa', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parque',
                'verbose_name_plural': 'Parques',
                'db_table': 'parque',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMIN', 'Administrador')], default='CLIENTE', max_length=10)),
                ('nivel_admin', models.IntegerField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='ImagenHospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('hospedaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.hospedaje')),
            ],
            options={
                'verbose_name': 'Imagen de hospedaje',
                'verbose_name_plural': 'Imágenes de hospedaje',
                'db_table': 'imagen_hospedaje',
            },
        ),
        migrations.CreateModel(
            name='ImagenParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.parque')),
            ],
            options={
                'verbose_name': 'Imagen de parque',
                'verbose_name_plural': 'Imágenes de parque',
                'db_table': 'imagen_parque',
            },
        ),
        migrations.AddField(
            model_name='hospedaje',
            name='parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedajes', to='core.parque'),
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('num_personas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo_visita', models.CharField(choices=[('CABANA', 'Cabaña'), ('CAMPING', 'Camping')], max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('EN_PROCESO', 'En proceso'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='ACTIVA', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospedaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='core.hospedaje')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='core.parque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'db_table': 'reservacion',
            },
        ),
        migrations.CreateModel(
            name='EmailNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BIENVENIDA', 'Bienvenida'), ('CONFIRMACION', 'Confirmación'), ('CANCELACION', 'Cancelación'), ('CAMBIO_P', 'Cambio de contraseña'), ('ASIGNACION_ADMIN', 'Asignación admin')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('reservacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='core.reservacion')),
            ],
            options={
                'verbose_name': 'Notificación por email',
                'verbose_name_plural': 'Notificaciones por email',
                'db_table': 'email_notificacion',
            },
        ),
        migrations.CreateModel(
            name='ServicioParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.parque')),
            ],
            options={
                'verbose_name': 'Servicio de parque',
                'verbose_name_plural': 'Servicios de parque',
                'db_table': 'servicio_parque',
            },
        ),
    ]
