# Generated by Django 6.0.1 on 2026-06-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioparque',
            name='icono',
        ),
    ]
