# Generated by Django 6.0.1 on 2026-05-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenhospedaje',
            name='url',
        ),
        migrations.RemoveField(
            model_name='imagenparque',
            name='url',
        ),
        migrations.AddField(
            model_name='imagenhospedaje',
            name='imagen',
            field=models.ImageField(default=1, upload_to='hospedajes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenparque',
            name='imagen',
            field=models.ImageField(default=1, upload_to='parques'),
            preserve_default=False,
        ),
    ]
