# Generated by Django 6.0.1 on 2026-06-01 03:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_imagenhospedaje_url_remove_imagenparque_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedaje',
            name='precio_por_noche',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio por noche de este hospedaje', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio total de la reservación (noches x precio por noche)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('NE', 'Prefiero no decir')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='parque_asignado',
            field=models.ForeignKey(blank=True, help_text='Parque administrado por este staff. Dejar en blanco para superusuarios.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_asignado', to='core.parque'),
        ),
    ]
