# Generated by Django 6.0.1 on 2026-05-27 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_imagenhospedaje_url_remove_imagenparque_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de la reservación', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
