# Generated by Django 6.0.1 on 2026-05-27 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservacion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio de la reservación', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
