# Generated by Django 6.0.1 on 2026-06-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hospedaje_precio_por_noche_reservacion_precio_total_and_more'),
        ('core', '0005_alter_reservacion_precio'),
    ]

    operations = [
    ]
