# Generated by Django 6.0.1 on 2026-06-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260601_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='precio',
        ),
    ]
